//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    @{KRATOS_APP_AUTHOR}
//

#if !defined(KRATOS_EHDTEST_APPLICATION_VARIABLES_H_INCLUDED )
#define  KRATOS_EHDTEST_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "containers/variable.h"

namespace Kratos
{
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, EPOTENCIAL )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, PERMITTIVITYPOS )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, PERMITTIVITYNEG )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, CONDUCTIVITYPOS )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, CONDUCTIVITYNEG )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, PCHARGE )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, SCHARGE )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, VCHARGE )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( EHDTEST_APPLICATION, EFIELD )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( EHDTEST_APPLICATION, EDISPLACEMENT )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( EHDTEST_APPLICATION, EFORCE )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( EHDTEST_APPLICATION, EFORCEPOS )
KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( EHDTEST_APPLICATION, EFORCENEG )
KRATOS_DEFINE_APPLICATION_VARIABLE( EHDTEST_APPLICATION, double, ICOEFFICIENT )

}

#endif	/* KRATOS_EHDTEST_APPLICATION_VARIABLES_H_INCLUDED */
